package com.g3g4x5x6.nuclei.model;

import lombok.Data;

import java.util.LinkedHashMap;
import java.util.LinkedList;


@Data
public class GlobalConfigModel {
    private LinkedList<String> target;
    private String list;
    private LinkedList<String> templates;
    private LinkedList<String> templateUrl;
    private LinkedList<String> workflows;
    private LinkedList<String> workflowUrl;
    private boolean validate;
    private boolean tl;
    private LinkedList<String> tags;
    private LinkedList<String> includeTags;
    private LinkedList<String> excludeTags;
    private LinkedList<String> includeTemplates;
    private LinkedList<String> excludeTemplates;
    private String severity;
    private String excludeSeverity;
    private String type;
    private String excludeType;
    private LinkedList<String> author;
    private String output;
    private boolean silent;
    private boolean noColor;
    private boolean json;
    private boolean includeRr;
    private boolean noMeta;
    private boolean noTimestamp;
    private String reportDb;
    private boolean matcherStatus;
    private String markdownExport;
    private String sarifExport;
    private String config;
    private String reportConfig;
    private LinkedList<LinkedHashMap<String, String>> header;
    private String var;
    private String resolvers;
    private boolean systemResolvers;
    private boolean passive;
    private boolean envVars;
    private String clientCert;
    private String clientKey;
    private String clientCa;
    private String interactshServer;
    private String interactshToken;
    private int interactionsCacheSize;
    private int interactionsEviction;
    private int interactionsPollDuration;
    private int interactionsCooldownPeriod;
    private boolean noInteractsh;
    private int rateLimit;
    private int rateLimitMinute;
    private int bulkSize;
    private int concurrency;
    private int headlessBulkSize;
    private int headlessConcurrency;
    private int timeout;
    private int retries;
    private int maxHostError;
    private boolean project;
    private String projectPath;
    private boolean stopAtFirstPath;
    private boolean stream;
    private boolean headless;
    private int pageTimeout;
    private boolean showBrowser;
    private boolean systemChrome;
    private boolean debug;
    private boolean debugReq;
    private boolean debugResp;
    private LinkedList<String> proxy;
    private String traceLog;
    private String errorLog;
    private boolean version;
    private boolean verbose;
    private boolean vv;
    private boolean templatesVersion;
    private boolean update;
    private boolean updateTemplates;
    private String updateDirectory;
    private boolean disableUpdateCheck;
    private boolean stats;
    private int statsJson;
    private int statsInterval;
    private boolean metrics;
    private int metricsPort;
}
