name: ci 
on:
  push:
    branches:
      - master 
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-minify-plugin
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install pip install mkdocs-git-committers-plugin-2
      - run: pip install mkdocs-git-authors-plugin
      - run: mkdocs gh-deploy
